spring:
  application:
    name: retail-store
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: username
    password: password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

server:
  servlet:
    context-path: /store
  tomcat:
    threads:
      max: 1000
    connection-timeout:
      30s
    max-connections: 3000
  port: 8084